services:
  essa-lib: # required for
    image: essa-lib:local
    container_name: essa-lib
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: app-dev
    volumes:
      - ./:/app

  test:
    image: essa-lib:local-test
    container_name: essa-lib-test
    restart: no
    build:
      context: .
      dockerfile: Dockerfile
      target: app-test
    command: 'php ./vendor/bin/phpunit'
    profiles: ["test"]
