name: Run PHPUNIT tests

on:
  workflow_call:
    inputs:
      compose_file:
        description: 'Docker compose file to run the container'
        required: false
        type: string
        default: docker-compose.yml
      runs_on:
        description: 'Where to run the job'
        required: false
        type: string
        default: ubuntu-24.04

defaults:
  run:
    shell: bash

jobs:
  unit_tests:
    name: Run UNIT tests
    runs-on: ${{ inputs.runs_on }}
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          mkdir -m 777 -p ./data
          docker compose -f docker-compose.yml run --build --rm -v ${PWD}/data:/app/data test --log-junit=./data/report.xml

      - name: Generate test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Unit Tests
          comment_mode: failures
          files: |
            ./data/*.xml
