name: Tag with next semantic version

on:
  workflow_call:
    inputs:
      runs_on:
        description: 'Where to run the job'
        required: false
        type: string
        default: ubuntu-24.04

defaults:
  run:
    shell: bash

jobs:
  tag:
    name: Tag with next semantic version
    runs-on:  ${{ inputs.runs_on }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create version and tag
        run: |
          for i in $(git tag -l --sort=-v:refname); do
            echo $i;
            if [[ $i =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              version=$(echo ${i} | awk -F '.' '{print $1 "." $2+1 "." $3}'); break
            fi
          done
          version=${version:=1.0.0}
  
          git tag "${version}"
          git push --tags
