name: Tag with next semantic version
description: Automatically creates new tag in semantic format

inputs:
  release_type:
    description: Should MINOR or PATCH version be boosted?
    required: true
    type: choice
    options:
      - minor
      - patch

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create minor version and tag
      if: ${{ inputs.release_type == 'minor' }}
      shell: bash
      run: |
        for i in $(git tag -l --sort=-v:refname); do
          echo $i;
          if [[ $i =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            version=$(echo ${i} | awk -F '.' '{print $1 "." $2+1 "." $3}'); break
          fi
        done
        version=${version:=1.0.0}

        git tag "${version}"
        git push --tags

    - name: Create patch version and tag
      if: ${{ inputs.release_type == 'patch' }}
      shell: bash
      run: |
        cacheVersion=
         for i in $(git tag -l --sort=-v:refname); do
           if [[ $i =~ "-" ]]; then
             if [[ -z "${cache_version}" ]]; then
               version=$(echo ${i} | awk -F '-' '{print $1 "-" $2+1}'); break;
             else
               version=${cache_version}-$((${i##*-}+1)); break;
             fi
           elif [[ $i =~ ^[0-9]+\.[0-9]+\.0$ ]]; then
             if [[ -z "${cache_version}" ]]; then
               version=${i}-1; break;
             else
               version=${cache_version}-1; break;
             fi
           elif [[ $i =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then cacheVersion=${cacheVersion:=$i}; fi
         done
         version=${version:=1.0.0-1}
        
         echo "VERSION=${version}" >> ${GITHUB_ENV}
         git tag "${version}"
         git push --tags
