name: Master CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  tag_version:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Tag version
        uses: ./.github/actions/tag
        with:
          release_type: minor
