name: Master CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  tag_version:
    uses: ./.github/actions/tag.yml # pfaffkam/essa/.github/actions/tag.yml@master
