name: Pull request CI

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

defaults:
  run:
    shell: bash

jobs:
  static_analyze:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run CSFixer analyze
        uses: ./.github/actions/csfixer
        with:
          compose_file: docker-compose.yml
          csfixer_config: .php-cs-fixer.dist.php

  unit_tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        uses: ./.github/actions/phpunit
        with:
          compose_file: docker-compose.yml
