name: Pull request CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

defaults:
  run:
    shell: bash

jobs:
  unit_tests:
    name: Run UNIT tests
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize')
    runs-on: ubuntu-24.04
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          mkdir -m 777 -p ./data
          docker compose -f docker-compose.yml run --build --rm -v ${PWD}/data:/app/data test --log-junit=./data/report.xml
          ls -la ./data

#          docker compose -f docker-compose.yml run --build --rm -v ${PWD}/data:/app/data test --log-junit=./data/report.xml
# https://github.com/marketplace/actions/publish-test-results

      - name: Generate test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: success() || failure()
        with:
          files: |
            data/*.xml
#          name: Unit Tests
#          path: data/report.xml
#          reporter: jest-junit


#      - name: Generate test results
#        uses: dorny/test-reporter@v1
#        if: success() || failure()
#        with:
#          name: Unit Tests
#          path: data/report.xml
#          reporter: jest-junit
